name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build -t my-docker-image:latest .
    
    - name: Log in to Docker Hub
      run: docker login -u ${{ ebarrientosr }} -p ${{ Brisa123$ }}

    - name: Push Docker Image
      run: docker push my-docker-image:latest
